// src/utils/translate_cn.js
// 英雄英文名称到中文名称的映射表
// 这是静态数据，如果Dota 2更新新英雄，需要手动在此处添加
export const HERO_CHINESE_NAMES = {
    "Anti-Mage": "敌法师",
    "Axe": "斧王",
    "Bane": "祸乱之源",
    "Bloodseeker": "血魔",
    "Crystal Maiden": "水晶室女",
    "Drow Ranger": "卓尔游侠",
    "Earthshaker": "撼地者",
    "Juggernaut": "主宰",
    "Mirana": "米拉娜",
    "Shadow Fiend": "影魔",
    "Morphling": "变体精灵",
    "Puck": "帕克",
    "Pudge": "屠夫",
    "Razor": "闪电幽魂",
    "Shadow Shaman": "暗影萨满",
    "Sven": "斯温",
    "Tiny": "小小",
    "Vengeful Spirit": "复仇之魂",
    "Windranger": "风行者",
    "Zeus": "宙斯",
    "Kunkka": "昆卡",
    "Lina": "莉娜",
    "Lion": "莱恩",
    "Nature's Prophet": "先知",
    "Necrophos": "瘟疫法师",
    "Queen of Pain": "痛苦女王",
    "Storm Spirit": "风暴之灵",
    "Templar Assassin": "圣堂刺客",
    "Viper": "冥界亚龙",
    "Winter Wyvern": "邪影芳灵", // 寒冬飞龙通常用此译名
    "Wraith King": "冥魂大帝",
    "Abaddon": "亚巴顿",
    "Alchemist": "炼金术士",
    "Ancient Apparition": "远古冰魄",
    "Arc Warden": "弧光",
    "Beastmaster": "兽王",
    "Brewmaster": "酒仙",
    "Bristleback": "钢背兽",
    "Broodmother": "育母蜘蛛",
    "Centaur Warrunner": "半人马战行者",
    "Chaos Knight": "混沌骑士",
    "Chen": "陈",
    "Clinkz": "克林克兹",
    "Clockwerk": "发条技师",
    "Dark Seer": "黑暗贤者",
    "Dark Willow": "邪影芳灵",
    "Dawnbreaker": "破晓之星",
    "Death Prophet": "死亡先知",
    "Disruptor": "干扰者",
    "Doom": "末日",
    "Dragon Knight": "龙骑士",
    "Dazzle": "戴泽",
    "Elder Titan": "远古巨神",
    "Ember Spirit": "灰烬之灵",
    "Enchantress": "魅惑魔女",
    "Enigma": "谜团",
    "Faceless Void": "虚空假面",
    "Grimstroke": "墨客",
    "Gyrocopter": "飞机",
    "Huskar": "哈斯卡",
    "Invoker": "祈求者",
    "Io": "艾欧",
    "Jakiro": "杰奇洛",
    "Keeper of the Light": "光之守卫",
    "Legion Commander": "军团指挥官",
    "Leshrac": "拉席克",
    "Lich": "巫妖",
    "Lifestealer": "噬魂鬼",
    "Lone Druid": "德鲁伊",
    "Luna": "露娜",
    "Lycan": "狼人",
    "Magnus": "马格纳斯",
    "Marci": "玛西",
    "Mars": "马尔斯",
    "Medusa": "美杜莎",
    "Meepo": "米波",
    "Monkey King": "齐天大圣",
    "Naga Siren": "娜迦海妖",
    "Night Stalker": "夜魔",
    "Nyx Assassin": "孽主刺客",
    "Ogre Magi": "食人魔魔法师",
    "Omniknight": "全能骑士",
    "Oracle": "神谕者",
    "Outworld Destroyer": "殁境神蚀者",
    "Pangolier": "石鳞剑士",
    "Phantom Assassin": "幻影刺客",
    "Phantom Lancer": "幻影长矛手",
    "Phoenix": "凤凰",
    "Primal Beast": "原初之兽",
    "Pugna": "帕格纳",
    "Riki": "力丸",
    "Rubick": "拉比克",
    "Sand King": "沙王",
    "Shadow Demon": "暗影恶魔",
    "Slardar": "斯拉达",
    "Slark": "斯拉克",
    "Snapfire": "森海飞霞",
    "Sniper": "狙击手",
    "Spectre": "幽鬼",
    "Spirit Breaker": "裂魂人",
    "Techies": "工程师",
    "Terrorblade": "恐怖利刃",
    "Timbersaw": "伐木机",
    "Tinker": "修补匠",
    "Treant Protector": "树精卫士",
    "Troll Warlord": "巨魔战将",
    "Tusk": "巨牙海民",
    "Underlord": "孽主",
    "Undying": "不朽尸王",
    "Ursa": "熊战士",
    "Venomancer": "剧毒术士",
    "Visage": "维萨吉",
    "Void Spirit": "虚无之灵",
    "Warlock": "术士",
    "Weaver": "编织者",
    "Witch Doctor": "巫医",
    "Pangolier": "石鳞剑士",
    "Silencer": "沉默术士",
};
